In [1]:
import numpy as np
from sklearn import datasets
from deepautoencoder import StackedAutoEncoder, mnist_data
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score, precision_score
import tensorflow as tf

In [2]:
train_x, train_y, test_x, test_y = mnist_data.read('data/train.amat', 'data/test.amat')

reading training file
reading test file


In [7]:
# train = np.genfromtxt('data/train.csv', delimiter=',')
# test = np.genfromtxt('data/test.csv', delimiter=',')
# train_x = train[:,:-1]
# train_y = train[:,-1]
# test_x = test[:,:-1]
# test_y = test[:,-1]
# iris = datasets.load_iris().data
# train_x = StandardScaler().fit_transform(train_x)
# test_x = StandardScaler().fit_transform(test_x)

In [12]:
model1 = StackedAutoEncoder(dims=[400], activations = ['linear'], noise='gaussian',
                           epoch=[650], loss='rmse', lr=0.005, batch_size=1500, print_step=30)
model2 = StackedAutoEncoder(dims=[5,6], activations=['relu', 'relu'], noise='gaussian', epoch=[1000,500], 
                            loss='rmse', lr=0.007, batch_size=50, print_step=200)

In [13]:
xx = model1.fit_transform(np.r_[train_x, test_x])
train_xx = xx[:len(train_x)]
test_xx = xx[len(train_x):]
print(train_xx.shape, test_xx.shape)

Layer 1
epoch 29: global loss = 101.92142486572266
epoch 59: global loss = 77.35276794433594
epoch 89: global loss = 62.23616409301758
epoch 119: global loss = 51.632808685302734
epoch 149: global loss = 43.340999603271484
epoch 179: global loss = 36.849151611328125
epoch 209: global loss = 31.406797409057617
epoch 239: global loss = 26.973377227783203
epoch 269: global loss = 23.171022415161133
epoch 299: global loss = 19.978246688842773
epoch 329: global loss = 17.25379753112793
epoch 359: global loss = 14.895711898803711
epoch 389: global loss = 12.906460762023926
epoch 419: global loss = 11.148634910583496
epoch 449: global loss = 9.659966468811035
epoch 479: global loss = 8.353558540344238
epoch 509: global loss = 7.22713041305542
epoch 539: global loss = 6.258431911468506
epoch 569: global loss = 5.4035234451293945
epoch 599: global loss = 4.6798224449157715
epoch 629: global loss = 4.034695625305176
[[ 0.01550753  0.09749793 -0.00550193 ..., -0.23058201  0.1956633
  -0.01948924]

In [7]:
pp = model2.fit_transform(iris)

Layer 1
epoch 199: global loss = 2.4214932918548584
epoch 399: global loss = 1.0057744979858398
epoch 599: global loss = 0.7559930086135864
epoch 799: global loss = 0.4162595272064209
epoch 999: global loss = 0.3130458891391754
Layer 2
epoch 199: global loss = 0.0663912445306778
epoch 399: global loss = 0.04874096438288689


In [6]:
train_xx[0]

array([ 1.31179571, -1.95800006,  1.01303792,  0.97272193, -0.17699262,
       -1.29262221, -1.31551278, -1.21083057, -1.50344634, -0.0965444 ,
        0.59724611, -0.6494962 , -3.49985695, -0.30785286, -0.23308799,
        0.21563172,  0.12909293,  1.39157319, -0.15972976, -0.57759953,
        0.1196399 , -1.54503727,  0.08533919,  0.68357611,  1.39569056,
       -0.86446357,  3.01472449,  0.52403623,  2.52302909, -0.16381824,
       -0.11957414,  0.06601053, -1.65876615,  1.64426935,  1.00454831,
       -0.64125896, -1.89955258, -0.89688486, -1.00098193, -0.03089035,
        1.39300621, -1.29888213, -0.09950158,  1.02288914, -1.22028673,
       -0.22380742, -2.15578198,  1.32637954,  0.93633687, -1.41742849,
       -1.98732305, -0.93380857,  0.82361984, -0.40955672, -0.7098611 ,
       -1.48103356,  1.15523326, -0.84218276, -1.78834713, -0.57677841,
        0.24555114, -0.22239256, -1.8537842 , -0.85183001, -1.30435252,
        1.4217844 ,  1.13165498,  0.37307471,  1.82772338, -0.12

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, accuracy_score

In [14]:
classifier = LogisticRegression()
classifier.fit(train_xx, train_y.astype(np.int32))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
accuracy_score(test_y.astype(np.int32), classifier.predict(test_xx))

0.40826000000000001

In [76]:
classifier.predict(test_xx)

array([2, 0, 2, ..., 6, 6, 4], dtype=int32)

In [57]:
test_y

array([ 6.,  0.,  6., ...,  7.,  6.,  7.])